#!/bin/bash

source /home/dc_group08/miniconda3/etc/profile.d/conda.sh
conda activate dc_env
# replace "master" with your branch name so that your code is run. You can also call another file to be run if you'd like.
python "/home/dc_group08/master/task.py" --job-dir 'jobs'
conda deactivate

exit 0
